#!/bin/bash

OUTDIR=bin-release

if [ "$1" = "-debug" ]; then
  OUTDIR=bin-debug
fi

#compc $* -source-path=src -output '$OUTDIR\SelectDevice.swc' 'SelectDevice'

mxmlc $* -output '$OUTDIR/Producer.swf' 'src/Producer.as'
mxmlc $* -output '$OUTDIR/Consumer.swf' 'src/Consumer.as'
