/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_videochat_VideoChat */

#ifndef _Included_cn_videochat_VideoChat
#define _Included_cn_videochat_VideoChat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_videochat_VideoChat
 * Method:    Init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_cn_videochat_VideoChat_Init
  (JNIEnv *, jclass);

/*
 * Class:     cn_videochat_VideoChat
 * Method:    Release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cn_videochat_VideoChat_Release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cn_videochat_VideoChat
 * Method:    SetVideoRender
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_cn_videochat_VideoChat_SetVideoRender
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     cn_videochat_VideoChat
 * Method:    OpenPublisher
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_videochat_VideoChat_OpenPublisher
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     cn_videochat_VideoChat
 * Method:    PausePublisher
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_cn_videochat_VideoChat_PausePublisher
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     cn_videochat_VideoChat
 * Method:    ClosePublisher
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cn_videochat_VideoChat_ClosePublisher
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cn_videochat_VideoChat
 * Method:    OpenPlayer
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_videochat_VideoChat_OpenPlayer
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     cn_videochat_VideoChat
 * Method:    PausePlayer
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_cn_videochat_VideoChat_PausePlayer
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     cn_videochat_VideoChat
 * Method:    ClosePlayer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cn_videochat_VideoChat_ClosePlayer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cn_videochat_VideoChat
 * Method:    CreateRender
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_cn_videochat_VideoChat_CreateRender
  (JNIEnv *, jclass);

/*
 * Class:     cn_videochat_VideoChat
 * Method:    SetRenderViewPort
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_cn_videochat_VideoChat_SetRenderViewPort
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     cn_videochat_VideoChat
 * Method:    RenderFrame
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cn_videochat_VideoChat_RenderFrame
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cn_videochat_VideoChat
 * Method:    RenderRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cn_videochat_VideoChat_RenderRelease
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
