/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_videochat_VideoChat */

#ifndef _Included_cn_videochat_VideoChat
#define _Included_cn_videochat_VideoChat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_videochat_VideoChat
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_videochat_VideoChat_Init
  (JNIEnv *, jobject);

/*
 * Class:     cn_videochat_VideoChat
 * Method:    OpenPublisher
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_videochat_VideoChat_OpenPublisher
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_videochat_VideoChat
 * Method:    ClosePublisher
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_videochat_VideoChat_ClosePublisher
  (JNIEnv *, jobject);

/*
 * Class:     cn_videochat_VideoChat
 * Method:    OpenPlayer
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_videochat_VideoChat_OpenPlayer
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_videochat_VideoChat
 * Method:    ClosePlayer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_videochat_VideoChat_ClosePlayer
  (JNIEnv *, jobject);

/*
 * Class:     cn_videochat_VideoChat
 * Method:    Release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_videochat_VideoChat_Release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
