/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_videochat_VideoChat_OnEventCallback */

#ifndef _Included_cn_videochat_VideoChat_OnEventCallback
#define _Included_cn_videochat_VideoChat_OnEventCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
